### ISSUE TITLE
Should create post be available in the menu if blog is disabled?

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/Municipio#17]
Should create post be available in the menu if blog is disabled? See screenshot. To me this seems like a bug.
<img width="976" alt="_lokal_miljo__custom_post_types_ _hoors_kommun_ _wordpress" src="https://cloud.githubusercontent.com/assets/34488/22248155/897c8242-e23d-11e6-83a4-0cb6eb2fffe6.png">

**Comment by Svanmark** [comment]
Looks like a bug, yes. I'm looking into it. Thanks.

**Comment by sebastianthulin** [comment]
No. It should not. It has been a bug for a while. This may also apply to "pages".
