### ISSUE TITLE
 error Failed at the node-sass@3.13.1 postinstall script

### ISSUE THREAD

**Issue by krishnan10kr** [helsingborg-stad/Municipio#171]
Hi,

When compiling using the latest stable node v14, I am getting below error.
--
 error Failed at the node-sass@3.13.1 postinstall script
--

Please check.

**Comment by sebastianthulin** [comment]
What branch are you using? Is i a new or older project?

**Comment by krishnan10kr** [comment]
I am using the latest, newer master.

**Comment by krishnan10kr** [comment]
Is there a suggested node version to compile this package?

**Comment by sebastianthulin** [comment]
Hi! 13.7 should work well.

**Comment by krishnan10kr** [comment]
Node 13.7 gives the same error.

**Comment by krishnan10kr** [comment]
@all, Used an older node version. It worked well. Thanks.
