### ISSUE TITLE
Uploading svg-logo not allowed

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/Municipio#20]
When adding an svg at wp/wp-admin/themes.php?page=acf-options-theme-options I get the message:

Sorry, this file type is not permitted for security reasons. / Tyvärr, denna filtyp inte tillåtet av säkerhetsskäl.

This has worked previously since we been able to upload a logo on hoor.se. I tried different things with the two upload_mimes filters. First I thought one of them was overriding the other, but adding svg to that one doesn't seem to help. At least not in my tests.

This is an Intranet site.

**Comment by sebastianthulin** [comment]
This is a WordPress bug introduced in 4.7.1. 

We made a patch for this issue that you can apply as a mu-plugin until WordPress team fixes the issue. 

<?php

function wp39550_disable_real_mime_check($data, $file, $filename, $mimes)
{
    $wp_filetype = wp_check_filetype($filename, $mimes);

    $ext = $wp_filetype['ext'];
    $type = $wp_filetype['type'];
    $proper_filename = $data['proper_filename'];

    return compact('ext', 'type', 'proper_filename');
}

add_filter('wp_check_filetype_and_ext', 'wp39550_disable_real_mime_check', 10, 4);
