### ISSUE TITLE
Remove highlight query parameter and notices

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/Municipio#3]
a5ca7b604c0a720916913de5c90cb22df8ce76fd adds ?highlight to all urls which we don't use in our theme as far as I know. Also `$post` is `false` which produces a lot of "Trying to get property of non-object" notices. This fixes the notices:

```php
if (!empty($post->post_mime_type)) {
```

I'm also pretty sure we don't want ?highlight in our URLs
![dokument___search_results___hoors_kommun](https://cloud.githubusercontent.com/assets/34488/18927479/754d299e-85bc-11e6-9b27-eaa74f1fb208.jpg)

**Comment by Svanmark** [comment]
Thanks! Looking into this asap.

**Comment by perifer** [comment]
I just realised that this is probably because we use Google CSE

**Comment by Svanmark** [comment]
Yes, that's probably why the $post variable is empty. I've made a commit (https://github.com/helsingborg-stad/Municipio/commit/db32b6235eeb7785f01ec64917ecaaafc5bd9f6c) to the develop branch that hopefully resolves the issue.

**Comment by perifer** [comment]
Works! I'm a bit curious what highlight is and why it isn't relevant when using Google. Also not sure why it's part of the text (Municipio/search_result/permalink_text) and not just the url Municipio/search_result/permalink_url.

**Comment by Svanmark** [comment]
It should work with Google as well but we need to test it further. It may be as easy as you do not have the hbg-prime.js enqued. 

However if you have the hbg-prime.js enqued the js will read the highlight query-string parameter and highlight matching words on the current page by wrapping them with <mark> tags.
