### ISSUE TITLE
[v3] Can't build assets since @helsingborg-stad/styleguide is not accessible on npm

### ISSUE THREAD

**Issue by jeanfredrik** [helsingborg-stad/Municipio#368]
I am not able to install the dependencies because @helsingborg-stad/styleguide is not available or inaccessible on NPM: https://www.npmjs.com/package/@helsingborg-stad/styleguide

Is the package private? Is there some other way to install it?

**Comment by jeanfredrik** [comment]
@sebastianthulin

**Comment by sebastianthulin** [comment]
Just following up on this. Did the above response resolve your issue?

**Comment by RickardAhlstedt** [comment]
Yes, it did, thank you :)
